// Code generated by fertilize; DO NOT EDIT.
package user

import (
  	"encoding/json"
	"fmt"
	"github.com/gitamped/seed/server"
	"github.com/gitamped/seed/validate"
) 
 
// CreateUserHandler validates input data prior to calling CreateUser
func (h UserServicer) CreateUserHandler(r server.GenericRequest, b []byte) (any, error) {
	var hr CreateUserRequest
	if err := json.Unmarshal(b, &hr); err != nil {
		return nil, fmt.Errorf("Unmarshalling data: %w", err)
	}

	if err := validate.Check(hr); err != nil {
		return nil, fmt.Errorf("validating data: %w", err)
	}

	return h.CreateUser(hr, r), nil
}
